### ISSUE TITLE
Setup Travis CI builds [DATAGEODE-267]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-geode#315]
**[John Blum](https://jira.spring.io/secure/ViewProfile.jspa?name=jblum)** opened **[DATAGEODE-267](https://jira.spring.io/browse/DATAGEODE-267?redirect=false)** and commented

Setup a Travis CI build environment for _*Spring Data for Apache Geode*_  (SDG) - `org.springframework.data:spring-data-geode`

---

**Reference URL:** https://jira.spring.io/browse/SGF-612

**Comment by jxblum** [comment]
Will open new Issue for Circle CI since Travis CI is unreliable.
