### ISSUE TITLE
Update CI jobs for Java 15 [DATAGEODE-372]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-geode#381]
**[Mark Paluch](https://jira.spring.io/secure/ViewProfile.jspa?name=mp911de)** opened **[DATAGEODE-372](https://jira.spring.io/browse/DATAGEODE-372?redirect=false)** and commented

---
No further details from [DATAGEODE-372](https://jira.spring.io/browse/DATAGEODE-372?redirect=false)

**Comment by jxblum** [comment]
CI builds have already been updated to Java 16.
