### ISSUE TITLE
Apply Java 8 types (e.g. Stream, Optional, Null annotations) and refactoring to the SDG codebase [DATAGEODE-2]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-geode#48]
**[John Blum](https://jira.spring.io/secure/ViewProfile.jspa?name=jblum)** opened **[DATAGEODE-2](https://jira.spring.io/browse/DATAGEODE-2?redirect=false)** and commented

This improvement involves changing the `GemfireOperations` and `GemfireTemplate` to return `Optional` values where `null` otherwise might be returned and to refactor the codebase to use the Java 8 Streams API to implement and streamline the functionality for maintainability

---
No further details from [DATAGEODE-2](https://jira.spring.io/browse/DATAGEODE-2?redirect=false)

**Comment by jxblum** [comment]
This task has mostly been complete and applied consistently across the entire SDG codebase.
