### ISSUE TITLE
Downgrade to Micrometer 1.8 on `3.0.x` branch

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-geode#571]
We need to stay on Micrometer 1.8 for the time being as Geode uses Micrometer internally. With the Micrometer 2.0 upgrade and the breaking API changes in Micrometer, Geode fails with `NoClassDefFoundError`.

**Comment by jxblum** [comment]
We need to downgrade to Micrometer `1.9.0`, which is in parallel development with Micrometer `2.0.0`.  Micrometer 1.9.0 serves as the bridge between Micrometer 1.x and 2.x.
