### ISSUE TITLE
Align Micrometer with Spring Data Build 3.x

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-geode#572]
Follow up to #571

**Comment by jxblum** [comment]
SDG alignment on Micrometer 2.0 as managed by Spring Data Build 3.0 is dependent on [GEODE-10045](https://issues.apache.org/jira/browse/GEODE-10045).

**Comment by jxblum** [comment]
I think this is a moot point now that the _Micrometer_ team has decided to move forward with _Micrometer_ `1.10` in place of _Micrometer_ `2.0`, given the backward compatibility issues that `2.0` caused for users.

It would also appear that our SD build parent is [aligned with](https://github.com/spring-projects/spring-data-build/blob/main/parent/pom.xml#L123) _Micrometer_ `1.10` now in the 3.0 line (see [here](https://github.com/spring-projects/spring-data-build/blob/main/parent/pom.xml#L24-L32)).

Closing this ticket as a side effect of the information above.
