### ISSUE TITLE
CacheServerApplication unable to connect to Gemfire cluster running apart from localhost

### ISSUE THREAD

**Issue by nayakmk** [spring-projects/spring-data-geode#634]
Hi @jxblum,

Can you please provide minimum configuration needed to connect a Gemfire CacheServerApplication as a REPLICATE_PROXY to a Gemfire/Geode cluster running apart from localhost ?

I have a cluster running which I am able to connect from ClientCacheApplication but the same configuration is not working for CacheServerApplication. 

Regards,
Malaya

**Comment by jxblum** [comment]
Hi @nayakmk - The main bit to connect a GemFire/Geode `CacheServer` application configured and bootstrapped with Spring is to set the `locators` property.

The first thing to keep in mind is, you should not confuse `Pool` [`locators` attribute](https://geode.apache.org/releases/latest/javadoc/org/apache/geode/cache/client/Pool.html#getLocators--) with the [`locators`](https://geode.apache.org/docs/guide/114/reference/topics/gemfire_properties.html) GemFire/Geode property (search for "locators" in the "Settings" column). These are not the same thing.

The former (i.e. `Pool` `locators` attribute) is used by cache clients (i.e. [`ClientCache` instances](https://geode.apache.org/releases/latest/javadoc/org/apache/geode/cache/client/ClientCache.html) that are configured and bootstrapped with SDG's [`ClientCacheApplication` annotation](https://docs.spring.io/spring-data/geode/docs/current/api/org/springframework/data/gemfire/config/annotation/ClientCacheApplication.html)) to connect to a GemFire/Geode cluster of servers. This is modeled in SDG Annotation configuration using the [`ClientCacheApplication.locator` attribute](https://docs.spring.io/spring-data/geode/docs/current/api/org/springframework/data/gemfire/config/annotation/ClientCacheApplication.html#locators--)  as well as the [`ClientCacheApplication.Locator` type](https://docs.spring.io/spring-data/geode/docs/current/api/org/springframework/data/gemfire/config/annotation/ClientCacheApplication.Locator.html). You should review the [ref doc](https://docs.spring.io/spring-data/geode/docs/current/reference/html/#bootstrap-annotation-config-client-server-applications) for more details. I recommend [configuration properties](https://docs.spring.io/spring-data/geode/docs/current/reference/html/#bootstrap-annotation-config-properties) whenever/wherever possible.

The later (i.e. GemFire/Geode `locators` property) is used by nodes (e.g. servers) to connect to the cluster as a peer member (i.e. [`Cache` instance](https://geode.apache.org/releases/latest/javadoc/org/apache/geode/cache/Cache.html)` or [`Locator` instance](https://geode.apache.org/releases/latest/javadoc/org/apache/geode/distributed/Locator.html); not a client). The GemFire/Geode `locators` property is not used by clients at all.

As you know, there are 2 ways to configure and bootstrap a peer member of a GemFire/Geode cluster using SDG. First is by using the `@PeerCacheApplication` annotation and the second is with the `@CacheServerApplication` annotation. Both create a `Cache` instance, peer node in the GemFire/Geode cluster, but `@CacheServerApplication` additionally creates Sockets on which cache clients (i.e. `ClientCache` instances`) can connect.

> NOTE: Clients cannot connect to a normal, data hosting peer `Cache` node that is not also serving clients, with an embedded [`CacheServer` instance](https://geode.apache.org/releases/latest/javadoc/org/apache/geode/cache/server/CacheServer.html).

> NOTE: Gfsh starts all servers as `CacheServers` so that client can connect by default, unless the `--disable-default-server` attribute is specified to the [`start server` command](https://geode.apache.org/docs/guide/114/tools_modules/gfsh/command-pages/start.html#topic_3764EE2DB18B4AE4A625E0354471738A).

As such, both SDG's `@PeerCacheApplication` ([here](https://docs.spring.io/spring-data/geode/docs/current/api/org/springframework/data/gemfire/config/annotation/PeerCacheApplication.html#locators--)) and `@CacheServerApplication` ([here](https://docs.spring.io/spring-data/geode/docs/current/api/org/springframework/data/gemfire/config/annotation/CacheServerApplication.html#locators--)) annotations have a `locators` attribute.

You can either set this in code, or as I would recommend, using the property `spring.data.gemfire.locators` property.

This property takes the format of: `hostOne[portOne],hostTwo[portTwo],...,hostN[portN]` where `host#` is the IP address or the DNS network name of the machine hosting the _Locator(s)_ and the `port#` is the port on which the Locators running at the host is listening.

If this property (or annotation attribute) is properly set, then the Spring configured/bootstrapped `@CacheServerApplication` should join an (existing) cluster, even if the other Locators/Servers were started with _Gfsh_.

The [_**Spring Boot for Apache Geode**_](https://github.com/spring-projects/spring-boot-data-geode#spring-boot-for-apache-geode) (SBDG) [reference documentation](https://docs.spring.io/spring-boot-data-geode-build/current/reference/html5/) is a bit more organized and detailed where configuring and bootstrapping servers are concerned. For example, on "[_Building Embedded (Peer & Server) Cache Applications_](https://docs.spring.io/spring-boot-data-geode-build/current/reference/html5/#geode-peercache-applications)".

This chapter even demonstrates configuring and bootstrapping multiple `CacheServers` with Spring (SBDG/SDG) as well as _Gfsh_, all connected together as peers in a cluster.

Hope this helps!

-John

**Comment by jxblum** [comment]
In summary (and short), you could do something along the following lines:

```java
@CacheServerApplication(name="ServerOne", port=12345, locators="hostOne{10335],hostTwo[10335]")
class MySpringDataGeodeCacheServerApplication {

    @Bean("MyReplicateRegion")
    public ReplicatedRegionFactoryBean<Object, Object> replicateRegion(GemFireCache gemfireCache) {

        ReplicatedRegionFactoryBean<Object, Object> replicateRegion = new ReplicatedRegionFactoryBean<>();

        replicateRegion.setCache(gemfireCache);
        replicateRegion.setreplicateRegion.setShortcut(RegionShortcut.REPLICATE_PROXY);

        return replicateRegion;
    }
}
```

The name of the `REPLICATE` Region must match all servers hosting the same `REPLICATE` Region, whether a proxy or not.

**Comment by jxblum** [comment]
> _On the servers point, if I have multiple spring server applications (pods) connected to a cluster and a cachewriter or listener is configured then will it notify all the servers or any one ? My Q is mainly coming from the write behind scenario._

**Comment by jxblum** [comment]
This doc describes the [event handling](https://geode.apache.org/docs/guide/114/developing/events/how_cache_events_work.html) for `REPLICATE` _Regions_ (scroll down) in general.

However, this is what I was specifically looking for...

https://geode.apache.org/docs/guide/114/developing/region_options/data_hosts_and_accessors.html

I would say that PROXY type Regions (whether REPLICATE or PARTITION) should receive events and if a `CacheCallback` was configured (e.g. `CacheListener` or `CacheWriter`) then it will be called, even for proxies.

Of course, this a GemFire/Geode behavior that has nothing to do with Spring. Spring can help you wire the `CacheCallback` to the [*_PROXY] Region accordingly though.

**Comment by jxblum** [comment]
> _The version of cluster running geode and the spring data geode version, needs to be compatible if connecting as Server application, along with the cluster Java version and Server application Java version. Is this right understanding ?_

Well, this has more to do with the Geode bits and specifically, protocols between peers (TCP, UDP, etc), or even clients and servers for that matter, than anything Spring does/does not do.

Client are the only major restriction that I know of.  That is, older clients can talk to same or newer servers, but newer clients cannot talk to older servers.

AFAIK, although don't quote me on it, older and newer GemFire/Geode servers can generally play together, hence GemFire/Geode's [rolling upgrade](https://geode.apache.org/docs/guide/114/getting_started/upgrade/upgrade_rolling.html) feature.

**Comment by jxblum** [comment]
Also, just a quick friendly reminder, this type of question is more aptly [asked on StackOverflow](https://stackoverflow.com/questions/tagged/spring-data-gemfire). We can continue the conversation to completion here, this time around.

Always happy to help. ;-)

**Comment by jxblum** [comment]
No problem! Again, happy to help. Wishing you all the best.
